In [1]:
import numpy as np
import matplotlib.pyplot as plt

## 연습문제 2.1.1

In [4]:
from sklearn.datasets import load_iris

iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [11]:
x2 = np.array(iris.data[1,:])
print(x2)

[4.9 3.  1.4 0.2]


## 연습문제 2.1.2

In [15]:
x = np.array(iris.data)
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

## 연습문제 2.1.3

1. Numpy를 사용해서 붓꽃 데이터 X의 전치행렬 $X^T$을 구한다.

In [16]:
xT = x.T
xT

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

2. Numpy를 사용해서 위 전치행렬을 다시 전치한 행렬을 구한다. 이 행렬과 원래 행렬 X을 비교한다.

In [17]:
xTT = xT.T
print(f'before : {xTT.shape}, Now : {x.shape}')

before : (150, 4), Now : (150, 4)


## 연습문제 2.1.4

1. 영벡터, 일벡터, 정방행렬, 대각행렬, 항등행렬, 대칭행렬의 예를 하나씩 만들어본다.

###### 영벡터: 요소들이 전부 0으로 이루어져있음
```
[[0,0,0],
[0,0,0],
[0,0,0]]
```
###### 일벡터: 요소들이 전부 1로 이루어져있음
```
[[1,1,1],
[1,1,1],
[1,1,1]]
```
###### 정방행렬: 행과 열의 개수가 같음
```
[[1,2,3],
[4,5,6],
[7,8,9]]
```
###### 대각행렬: 대각선에만 값이 있음
```
[[1,0,0],
[0,2,0],
[0,0,3]]
```
###### 항등행렬: 대각 행렬 중 값이 1인 행렬
```
[[1,0,0],
[0,1,0],
[0,0,1]]
```
###### 대칭행렬: 전치를 해도 원래의 행렬과 같은 행렬
```
[[1,2,3],
[2,1,2],
[3,3,1]]
```

In [19]:
# 위의 대칭행렬 증명
test = np.array([[1,2,3],[2,1,3],[3,2,1]])
test.T

array([[1, 2, 3],
       [2, 1, 2],
       [3, 3, 1]])

2. 위의 벡터와 행렬을 Numpy로 나타내본다.

In [32]:
# 영벡터: 요소들이 전부 0으로 이루어져있음
zero_vector = np.zeros((3,3))
print(zero_vector)
# 일벡터: 요소들이 전부 1로 이루어져있음
one_vector = np.ones((3,3))
print(one_vector)
# 정방행렬: 행과 열의 개수가 같음
square = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(square)
# 대각행렬: 대각선에만 값이 있음
dig = np.diag([1,2,3])
print(dig)
# 항등행렬: 대각 행렬 중 값이 1인 행렬
eyes = np.eye(3)
print(eyes)
# 대칭행렬: 전치를 해도 원래의 행렬과 같은 행렬
symmetric = np.array([[1,2,3],[2,1,3],[3,2,1]])
print(symmetric)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3]
 [2 1 3]
 [3 2 1]]


## 연습문제 2.2.1
A, B, C 세 회사의 주식은 각각 100만원, 80만원, 50만원이다. 이 주식을 각각 3주, 4주, 5주를 매수할 때 필요한 금액을 구하고자 한다.
1. 주식의 가격과 수량을 각각 p벡터, n벡터로 표시하고 넘파이로 코딩한다.
2. 주식을 매수할 때 필요한 금액을 곱셈으로 표시하고 넘파이 연산으로 그 값을 계산한다.

In [33]:
# 1번
p = np.array([100,80,50])
n = np.array([3,4,5])

In [34]:
# 2번
need_money = (p*10000)*n
print(need_money)

[3000000 3200000 2500000]


## 연습문제 2.2.2
벡터 x의 평균 제거 벡터는 다음과 같이 계산함을 증명하라.
$$x-\frac{1}{N}1_{N}^{T}x1_{N}$$

In [39]:
x = np.arange(10)
x-x.mean()

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [58]:
N = len(x)
x-(np.ones(N)@x*np.ones(N).T) / N # np.ones(N)@x -> 상수가 된다.

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

## 연습문제 2.2.3

In [59]:
from sklearn.datasets import load_digits
X = load_digits().data

1. 내적을 이용하여 첫 번째 이미지와 10번째 이미지의 유사도를 구하라.

In [60]:
X[0].T @ X[9]

2807.0

2. 내적을 이용하여 모든 이미지의 조합에 대해 유사도를 구하라. 어떻게 구현하는 것이 효율적일까?

In [63]:
X.shape

(1797, 64)

In [62]:
X@X.T

array([[3070., 1866., 2264., ..., 2812., 3006., 2898.],
       [1866., 4209., 3432., ..., 3906., 3083., 3307.],
       [2264., 3432., 4388., ..., 4005., 3063., 3697.],
       ...,
       [2812., 3906., 4005., ..., 5092., 3729., 4598.],
       [3006., 3083., 3063., ..., 3729., 4316., 3850.],
       [2898., 3307., 3697., ..., 4598., 3850., 4938.]])

## 연습문제 2.2.4


In [64]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])

1. A와 B가 위와 같을 때 AB를 연습장에 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다.
2. 순서를 바꾸어 BA를 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. BA가 AB와 같은가?
3. A, B가 다음과 같을 때, AB, BA를 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. AB, BA 모두 계산 가능한가?    
A = [1,2,3], B = [[4,7],[5,8],[6,9]]
4. A, B가 다음과 같을 때, AB, BA를 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. AB, BA 모두 계산 가능한가? BA의 결과가 AB와 같은가?    
A = [[1,2],[3,4]], B = [[5,6],[7,8]]
5. A가 다음과 같을 때, $AA^T$와 $A^TA$를 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. $AA^T$와 $A^TA$의 크기는 어떠한가? 항상 정방행렬이 되는가?    
A = [[1,2],[3,4],[5,6]]
6. x가 다음과 같을 때, $x^Tx$와 $xx^T$를 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. $x^Tx$와 $xx^T$의 크기는 어떠한가? 어떤 것이 스칼라이고 어떤 것이 정방행렬인가?    
x = [[1],[2],[3]]

![틈새수학-3 2](https://user-images.githubusercontent.com/63278762/126076427-6a33c947-4ab8-4f70-92f0-659aa9f202f9.jpg)
![틈새수학-4](https://user-images.githubusercontent.com/63278762/126076431-b6f63480-7abf-4e2f-ba22-c0b230c5810b.jpg)

In [66]:
# 1
A@B

array([[22, 28],
       [49, 64]])

In [67]:
# 2
B@A

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [69]:
# 3
A = np.array([1,2,3])
B = np.array([[4,7],[5,8],[6,9]])
print(A@B)
print(B@A) # BA는 계산이 불가하다.

[32 50]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [70]:
# 4
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A@B)
print(B@A)
# AB와 BA의 결과는 같지 않다.

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [71]:
# 5
A = np.array([[1,2],[3,4],[5,6]])
print(A@A.T)
print(A.T@A)
# 크기가 항상 정방 행렬로 같다.

[[ 5 11 17]
 [11 25 39]
 [17 39 61]]
[[35 44]
 [44 56]]


In [72]:
# 6
x = np.array([[1],[2],[3]])
print(x.T@x) # 스칼라
print(x@x.T) # 정방행렬

[[14]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


## 연습문제 2.2.5

1. 길이가 같은 일벡터와 행벡터의 곱은 행벡터 x를 반복하여 가지는 행렬과 같음을 보여라.

In [87]:
one_vector = np.ones((5,1))
x = np.arange(5).reshape((1,5)) # array([[0, 1, 2, 3, 4]])
one_vector@x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

2. 행렬 X가 있을 때, 이 행렬의 각 열의 평균으로 이루어진 벡터 $\widetilde{x}$가 다음과 같음을 보여라.(질문)
$$\widetilde{x} = \frac{1}{N}X^T1_{N}$$

In [113]:
x = np.arange(10).reshape((2,5))
N,M = x.shape
mean_vector = np.array([np.mean(i) for i in x.T])
compare_vector=(x.T@np.ones(N))/N
print(mean_vector)
print(compare_vector)

[2.5 3.5 4.5 5.5 6.5]
[2.5 3.5 4.5 5.5 6.5]


3. 행렬 $\widetilde{X}$는 동일한 벡터 $\widetilde{x}^T$를 N개 누적하여 만든 행렬이다. 즉 각 열의 모든 값이 그 열의 평균으로 이루어진 행렬이다. 이때 $\widetilde{X}$가 다음과 같음을 보여라. (질문)
$$\widetilde{X} = \frac{1}{N}1_{N}1_{N}^{T}X$$

4. 다음 코드를 실행하면 붓꽃 전체 데이터를 모두 벡터로 변환하여 하나의 넘파이 행렬 X를 만든다. 이 데이터로 행렬$\widetilde{X}$의 값을 계산하라.

In [128]:
from sklearn.datasets import load_iris
X = load_iris().data

In [132]:
N,M = X.shape
np.ones(N)@np.ones(N).T*X

array([[ 765.,  525.,  210.,   30.],
       [ 735.,  450.,  210.,   30.],
       [ 705.,  480.,  195.,   30.],
       [ 690.,  465.,  225.,   30.],
       [ 750.,  540.,  210.,   30.],
       [ 810.,  585.,  255.,   60.],
       [ 690.,  510.,  210.,   45.],
       [ 750.,  510.,  225.,   30.],
       [ 660.,  435.,  210.,   30.],
       [ 735.,  465.,  225.,   15.],
       [ 810.,  555.,  225.,   30.],
       [ 720.,  510.,  240.,   30.],
       [ 720.,  450.,  210.,   15.],
       [ 645.,  450.,  165.,   15.],
       [ 870.,  600.,  180.,   30.],
       [ 855.,  660.,  225.,   60.],
       [ 810.,  585.,  195.,   60.],
       [ 765.,  525.,  210.,   45.],
       [ 855.,  570.,  255.,   45.],
       [ 765.,  570.,  225.,   45.],
       [ 810.,  510.,  255.,   30.],
       [ 765.,  555.,  225.,   60.],
       [ 690.,  540.,  150.,   30.],
       [ 765.,  495.,  255.,   75.],
       [ 720.,  510.,  285.,   30.],
       [ 750.,  450.,  240.,   30.],
       [ 750.,  510.,  240.,   60.],
 

## 연습문제 2.2.6

In [139]:
A = np.array([1,2]).reshape((1,2))
B= np.array([[1,2],[3,4]])
C = np.array([[5],[6]]).reshape((2,1))

In [140]:
A@B@C

array([[95]])

In [142]:
C@A@B

array([[35, 50],
       [42, 60]])

## 연습문제 2.2.7

![틈새수학-6](https://user-images.githubusercontent.com/63278762/126081868-719bd3d2-8d45-44c1-8daf-57f2f222bef6.jpg)

In [143]:
X = np.array([[1,2,3],[4,5,6]])
w = np.array([[2],[3],[4]])
X@w

array([[20],
       [47]])

## 연습문제 2.2.9

![틈새수학-7](https://user-images.githubusercontent.com/63278762/126081946-2011f5b8-5c29-4341-af2a-a1f1738218a2.jpg)

## 연습문제 2.2.10

![틈새수학-7](https://user-images.githubusercontent.com/63278762/126081946-2011f5b8-5c29-4341-af2a-a1f1738218a2.jpg)

## 연습문제 2.2.11

![틈새수학-9](https://user-images.githubusercontent.com/63278762/126082579-233c1dcc-852e-4300-9b88-7210da48cf1a.jpg)

## 연습문제 2.2.12

In [151]:
A = np.arange(1, 10).reshape(3, 3)
x = np.array([1, 2, 3])

In [152]:
x.T@A@x

228

In [153]:
(x.T@(A+A.T)@x)/2

228.0

## 연습문제 2.2.13

![틈새수학-14](https://user-images.githubusercontent.com/63278762/126085519-6a4a5ba8-a8d9-48d4-878c-1a84c4cfe73f.jpg)

## 연습문제 2.2.14

![틈새수학-13](https://user-images.githubusercontent.com/63278762/126085385-315ba003-0c45-4676-b6c2-987d1425089a.jpg)

## 연습문제 2.3.1

![틈새수학-12](https://user-images.githubusercontent.com/63278762/126085037-5ec291b7-7a64-49fa-8d78-24a2f71271d8.jpg)

## 연습문제 2.3.2

![_-49](https://user-images.githubusercontent.com/63278762/126084956-cc909d65-14a9-4faf-ae5d-ad17d0b470ac.jpeg)

## 연습문제 2.3.3

![틈새수학-12 2](https://user-images.githubusercontent.com/63278762/126085651-5676d63f-7a72-4b04-895e-b8c19b4b063d.jpg)

## 연습문제 2.3.4

$(X^TX)^-1$은 $X^TX$의 역행렬로 $X^TX$와 곱하면 항등 행렬이 된다.

## 연습문제 2.3.5

![_-45](https://user-images.githubusercontent.com/63278762/126085783-c0b51707-f158-4a07-9b15-bb38292d8802.jpeg)

## 연습문제 2.3.6

![틈새수학-16](https://user-images.githubusercontent.com/63278762/126086086-b7420972-d0fc-41d3-b4ed-29b5d73459d8.jpg)

## 연습문제 2.3.7
다음 행렬이 양의 정부호인지, 양의 준정부호인지 혹은 두가지 중 어느것도 아닌지 판단하라. 그리고 행렬의 대각합과 행렬식을 구하라.

In [155]:
# 1
A = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
print(A)
# 대각합
print(np.trace(A))
# 행렬식
print(np.linalg.det(A))

[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
6
4.0


![틈새수학-17](https://user-images.githubusercontent.com/63278762/126086563-c39816f3-c79b-4c9b-bba8-6cdf3721a39a.jpg)

In [156]:
# 2
B = np.array([[1,2],[3,4]])
print(B)
# 대각합
print(np.trace(B))
# 행렬식
print(np.linalg.det(B))

[[1 2]
 [3 4]]
5
-2.0000000000000004


![틈새수학-18](https://user-images.githubusercontent.com/63278762/126086572-4ee0f585-1373-4432-be1a-38874f9bd8c1.jpg)


## 연습문제 2.4.1

In [163]:
A = np.diag([1,2,4])
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 4]])

In [164]:
Ainv = np.linalg.inv(A)
Ainv

array([[1.  , 0.  , 0.  ],
       [0.  , 0.5 , 0.  ],
       [0.  , 0.  , 0.25]])

## 연습문제 2.4.3

In [176]:
import math
# 1
A = np.diag([2,1])
print(np.linalg.inv(A))
# 2
A = np.array([[1/math.sqrt(2), -1/math.sqrt(2)],[1/math.sqrt(2),1/math.sqrt(2)]])
print(np.linalg.inv(A))
# 3
A = np.array([[3/math.sqrt(13), -1/math.sqrt(2)],[2/math.sqrt(13),1/math.sqrt(2)]])
print(np.linalg.inv(A))
# 2
A = np.array([[1,1,0],[0,1,1],[1,1,1]])
print(np.linalg.inv(A))

[[0.5 0. ]
 [0.  1. ]]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[[ 0.72111026  0.72111026]
 [-0.56568542  0.84852814]]
[[ 0. -1.  1.]
 [ 1.  1. -1.]
 [-1.  0.  1.]]


## 연습문제 2.4.4

AB = I라는 이야기는 A와 B의 관계가 역행렬 관계라는 이야기이다. 따라서 AB=I이면 BA=I이다.

## 연습문제 2.4.5

In [177]:
from sklearn.datasets import load_boston
import numpy as np

boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 'CRIM', 'NOX', 'RM', 'AGE'
b = y[:4]

Ainv = np.linalg.inv(A)
w = Ainv @ b
print('가중치', w)

# [-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]

가중치 [-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]


## 연습문제 2.4.6

In [184]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
y = y.reshape(len(y),1)

In [179]:
Apinv = np.linalg.inv(X.T@X)@X.T
Apinv

array([[ 1.09231858e-04,  8.96511045e-05,  1.43390247e-04, ...,
         9.92573160e-05,  9.76945713e-05,  9.00841038e-05],
       [-4.72690165e-05, -1.21875540e-04, -1.63389620e-04, ...,
         9.24841138e-05,  8.61893367e-05,  1.02954680e-04],
       [-1.04927299e-03,  9.41663987e-05,  2.53311215e-04, ...,
         1.16960096e-04,  1.09836326e-04,  9.11452898e-07],
       ...,
       [-5.61436625e-04, -2.96418946e-04, -4.00322073e-04, ...,
         1.85404958e-03,  1.85182324e-03,  2.21824093e-03],
       [ 3.37924487e-06,  1.47110306e-06, -4.60821286e-06, ...,
        -1.20096147e-05, -1.20573000e-05, -6.30925747e-06],
       [-3.79769286e-04, -1.98270828e-04, -3.32088952e-04, ...,
        -7.97353922e-04, -7.65739790e-04, -7.77591904e-04]])

In [186]:
A_plus = Apinv@y

In [190]:
X @ A_plus

array([[29.09826353],
       [24.50227548],
       [31.22742641],
       [29.7071035 ],
       [29.56479572],
       [25.29376224],
       [21.53041161],
       [19.10333426],
       [11.09336136],
       [18.25932202],
       [19.33401835],
       [20.4158837 ],
       [19.66602494],
       [20.66457506],
       [20.52388857],
       [20.11740519],
       [21.53034318],
       [18.36426279],
       [15.75504665],
       [18.82001911],
       [13.36203016],
       [18.82895424],
       [17.8884165 ],
       [15.26772521],
       [17.18318797],
       [13.81345441],
       [16.64674785],
       [16.1607536 ],
       [21.87232168],
       [23.39911229],
       [12.92645767],
       [19.27385466],
       [10.60202091],
       [15.02702479],
       [14.86361453],
       [22.55028082],
       [21.02570495],
       [22.07385902],
       [22.30111817],
       [31.18519291],
       [34.74543406],
       [28.28052928],
       [24.25528702],
       [23.99006396],
       [21.95417691],
       [20

In [193]:
x, resid, rank, s = np.linalg.lstsq(X, y, rcond=None)

In [195]:
resid, np.linalg.norm(X @ x - y) ** 2

(array([12228.04626104]), 12228.046261044006)

In [197]:
s

array([1.25851816e+04, 3.44597406e+03, 6.45757109e+02, 4.02050461e+02,
       1.58964612e+02, 1.21502936e+02, 9.04652420e+01, 7.79311708e+01,
       6.50828345e+01, 2.46251803e+01, 1.80945451e+01, 5.51505065e+00,
       1.48096916e+00])